<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function bag_importer_menu() {
  return array(
    'admin/islandora/tools/bagimporter' => array(
      'title' => 'Bag Importer',
      'description' => 'Configure the Bag Importer.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bag_importer_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_islandora_importer().
 */
function bag_importer_islandora_importer() {
  return array(
    'bag_importer' => array(
      'title' => t('Bag Importer'),
      'class' => 'BagBatchImporter',
    ),
  );
}

/**
 * Implements hook_help().
 */
function bag_importer_help($path, $args) {
  if ($path == 'islandora/object/%islandora_object/manage/collection/batch_import') {
    return '<p>' . t('The "Bag Importer" needs help text') . '</p>';
  }
}
